### PR TITLE
📚 DOCS: Add Learn Python Programming book to gallery

### PR DESCRIPTION
**Pull request by durgeshsamariya**
Fixed logo path.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
oops, checked the website, but not the logo. Can you fix the conflict

**Comment by durgeshsamariya** [comment]
@chrisjsewell Thanks for the comment. I also seen and already pull request submitted.

Cheers.

**Comment by chrisjsewell** [comment]
yep but you still need to resolve the merge conflict

**Comment by choldgraf** [comment]
I just resolved the conflict via the github ui 👍

**Pull request merged**
