### PR TITLE
📚 DOCS: Added the Jupyter Book HelioML

### PR DESCRIPTION
**Pull request by mbobra**
I'm sorry @jmason86 and I didn't get to this before PR #181 was merged.

### CODE REVIEW

**Comment by choldgraf** [comment]
hey @mbobra - thanks for the PR! I initially hesitated to add this to the gallery only because it's using the old version of Jupyter Book rather than the new one. Do you have any plans to update to the new Jupyter Book?

**Comment by mbobra** [comment]
Ah yes, sorry about that. We plan to update it in January. I am totally happy to make a new PR then if you like. 

We tried to update it a couple months ago and messed everything up so we reverted back to an older version. We have too many things going on in December to try again but we have time in January.

**Comment by choldgraf** [comment]
amazing! many thanks for the great book, and for the update :-)

**Comment by choldgraf** [comment]
amazing! many thanks for the great book, and for the update :-)

**Comment by mbobra** [comment]
@choldgraf I'm so sorry -- I did some more reorganizing after the PR. That's why the logo isn't showing up in the gallery. The gallery.yml file should read:

```yml
- name: Machine Learning, Statistics, and Data Mining for Heliophysics
  website: https://helioml.org
  repository: https://github.com/HelioML/HelioML/
  image: https://github.com/HelioML/HelioML/blob/master/book/logo.png
```

Should I open another PR?

**Comment by choldgraf** [comment]
yep - can you open a new one to correct it?

**Pull request merged**
