### PR TITLE
Update gallery.yml

### PR DESCRIPTION
**Pull request by bronwojtek**
Hi! I have a new book which I would like, if possible, to be listed in the gallery. thx - Wojciech

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Cheers @bronwojtek looks good, but your image is not working. Have a look at the url of others in the file, it needs to be a slightly different format

**Comment by bronwojtek** [comment]
Hi! I corrected the path to the logo. I am completely new to github, so I opened a new request. Thx for your assistance - Wojciech

**Comment by choldgraf** [comment]
I just merged #430 so closing this - thanks for the addition!

**Comment by bronwojtek** [comment]
Dear Chris,

As I have successfully published neuralnets-in-raw-python 

https://bronwojtek.github.io/neuralnets-in-raw-python/docs/index.html 

as a Juputer Book (where in subsequents chapgers Binder works no problem!), I am trying to make a Jupyter Book from my other lectures: 

https://bronwojtek.github.io/matematyka-dysketna-python/docs/index.html 

I have followed exactly the same procedure as before, the book looks fine, but for some possible stupidity on my side Binder (or Colab) do not find the path to the Jupyter notebooks. The message is "Could not resolve ref for gh:bronwojtek/matematyka-dyskretna-python/master. Double check your URL. GitHub recently changed default branches from "master" to "main". Did you mean the "main" branch?”.  But I do have “master” and not “main”, and all is as in my previous successful submittion. 

As this may be some typical problem, your help would be greatly appreciated.

With mu best regards - Wojciech

**Comment by chrisjsewell** [comment]
See https://github.com/bronwojtek/matematyka-dysketna-python/pull/1 😄

**Pull request closed without merging**
