### PR TITLE
📚 DOCS: Add Development Data Partnership to gallery

### PR DESCRIPTION
**Pull request by g4brielvs**
Adding the [Development Data Partnership](https://docs.datapartnership.org/) to the gallery :tada:.

### CODE REVIEW

**Comment by choldgraf** [comment]
hmmm - looks like https://github.com/datapartnership/docs doesn't exist?

**Comment by g4brielvs** [comment]
@choldgraf Thank you for review this! Unfortunately `docs` is a private repository on GitHub, but the page can be seen [here](https://docs.datapartnership.org/).

**Comment by choldgraf** [comment]
could you remove the `repository` entry then? It will point to a broken link!

**Comment by chrisjsewell** [comment]
nice emoji use! 🔥

**Comment by choldgraf** [comment]
I thought the same thing, that is super impressive 😄

**Comment by g4brielvs** [comment]
@choldgraf Done! Please let me know if anything else is needed. And thank you for Jupyter Book!

**Comment by choldgraf** [comment]
hmmm now https://docs.datapartership.org/ isn't working for me 🤔 could it be temporarily down?

**Comment by g4brielvs** [comment]
@choldgraf Sorry about the typo! 😨

**Comment by choldgraf** [comment]
thanks @g4brielvs !

**Pull request merged**
