### PR TITLE
📚 DOCS: Update gallery.yml

### PR DESCRIPTION
**Pull request by bvanderlei**
I've added an entry for my book, "Jupyter Guide to Linear Algebra".  I'm still working on minor additions and editing, but the book is useful in its current form and is approaching completion.  Thank you for your work on the tools to make this possible.  Jupyter book has provided a great authoring experience for the subject.

### CODE REVIEW

**Comment by choldgraf** [comment]
looks great! thanks :-)

**Comment by lu-kas** [comment]
@bvanderlei looks great! How did you manage to have the matplotlib figures centered?

**Comment by bvanderlei** [comment]
@lu-kas I thought that was the default behavior.  The code for the figures is all visible in the notebooks and I don't believe I used any configuration options that would have had an effect.  Note that I am not using the figure directive, or any directives at this point.  The results might be different if the matplotlib output is combined with directives.

**Comment by lu-kas** [comment]
@bvanderlei from a quick look at your config, I also do not see anything special. Yet, if you have a look at the documentation book

https://jupyterbook.org/content/code-outputs.html

the python generated output seems to be left aligned. Although there is not a simple plain matplotlib figure output.

@choldgraf do you have any idea?

Thanks!

**Pull request merged**
