### PR TITLE
DOC: Add pyhf user guide and tutorial to gallery

### PR DESCRIPTION
**Pull request by matthewfeickert**
Add the [pyhf](https://github.com/scikit-hep/pyhf) [user guide and tutorial](https://pyhf.github.io/pyhf-tutorial/) to the Gallery of Jupyter Books.

c.f. https://github.com/scikit-hep/pyhf

(cc @lukasheinrich @kratsg)

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@chrisjsewell @choldgraf This is ready for review. (Sorry, not trying to be spammy or demanding, I just know that you're both very busy and have more GitHub notifications then anyone should be reasonably expected to handle so thought I'd ping.)

**Comment by matthewfeickert** [comment]
@chrisjsewell @choldgraf gentle ping on this.

**Comment by chrisjsewell** [comment]
Oh yeh sorry @matthewfeickert cheers!

**Comment by matthewfeickert** [comment]
Thanks @chrisjsewell! Nothing to be sorry about!

**Pull request merged**
