### PR TITLE
[blog] Update on Project for 2022

### PR DESCRIPTION
**Pull request by mmcky**
This PR adds an update to the project for the executable books blog.

### CODE REVIEW

**Comment by mmcky** [comment]
@choldgraf there seems to be a lot of false positives re: link checker.

**Comment by rowanc1** [comment]
So cool! Enjoyed the read. :) So much going on, really excited about the power of the foundational tools and community we are building here. 🚀

**Comment by mmcky** [comment]
@rowanc1 that was super fast! ❤️ thanks for checking it out. 

Once I figure out how the blog works I'll post the html :-)

**Comment by mmcky** [comment]
@choldgraf the blog entry isn't showing up in the `rtd` preview. What am I missing?

**Comment by stevejpurves** [comment]
@mmcky there is a build error in the docs, looks unrelated but is marked as critical, could that be affecting the build?
image


Also on link-checker - look like its failing on various PRs with `Network Error` - is that because a github PAT has expired?

**Comment by mmcky** [comment]
> @mmcky there is a build error in the docs, looks unrelated but is marked as critical, could that be affecting the build? image
> 
> Also on link-checker - look like its failing on various PRs with `Network Error` - is that because a github PAT has expired?

🤔 thanks @stevejpurves -- I'll try and track that down in the morning.

**Comment by choldgraf** [comment]
I wanna say that I've run into issues like this before with GitHub, and I _think_ that the solution was to run Lychee with the `-i` or `--insecure` flag, which lets it check links that don't have a TLS certificate working properly.

Here's more about lychee: https://github.com/lycheeverse/lychee#commandline-parameters

And you can pass arguments to lychee via the action like so: https://github.com/lycheeverse/lychee-action#passing-arguments

**Comment by mmcky** [comment]
OK the blog post is working now on the PR so I will merge this. 

@choldgraf this link checker is fragile perhaps we should just run once a day on a schedule instead?

**Pull request merged**
