### PR TITLE
Adding the astroML interactive book

### PR DESCRIPTION
**Pull request by bsipocz**
Logo may need adjustments, waiting for CI rendering

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Thanks @bsipocz! Let me know when you are happy with the logo

**Comment by bsipocz** [comment]
This is good to go now.

**Comment by chrisjsewell** [comment]
I guess this is GTG 😄

**Comment by bsipocz** [comment]
yes, both this one and the networkx one are freshly rebased and are good to go.

**Review by chrisjsewell — APPROVED** [review]
Cheers!

**Pull request merged**
